# -*- coding: utf-8 -*-
import clr

clr.AddReference('RevitAPI')
import Autodesk
from Autodesk.Revit import DB

import sys
sys.path.append(r"C:\Program Files (x86)\IronPython 2.7\Lib")
sys.path.append(r"X:\01_Скрипты\05_BIM_Модули")
from ingp import doc, is_dynamo
from ingp_errors import CustomWarningError
from ingp_dialog import mbox2

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
import collections
import math
clr.AddReference("System.Windows.Forms")

import System
from System.Collections.Generic import List

if "__revit__" in __builtins__.keys():
    is_dynamo = False

    uiapp = __revit__    # type: ignore # noqa
    app = __revit__.Application    # type: ignore # noqa
    uidoc = __revit__.ActiveUIDocument    # type: ignore # noqa
    doc = __revit__.ActiveUIDocument.Document    # type: ignore # noqa
else:
    is_dynamo = True

    uiapp = DocumentManager.Instance.CurrentUIApplication
    app = uiapp.Application
    uidoc = uiapp.ActiveUIDocument
    doc = DocumentManager.Instance.CurrentDBDocument

def main():
    return

res = 'Что-то пошло не так'
try:
    res = main()
    
except CustomWarningError as e:
    print e.message
    
except Exception as e:
    import traceback
    msg = traceback.format_exc()
    print e.message
    print msg


# Закрепление элемента
def pinned_links(elements):
    for element in elements:
        element.Pinned = True


# Получение значения параметра
def get_parameter_value3(parameter):
    """
    В аргумент подается экз-р класса Parameter
    """
    if isinstance(parameter, DB.Parameter):
        storage_type = parameter.StorageType
        if storage_type == DB.StorageType.Integer:
            return parameter.AsInteger()
        elif storage_type == DB.StorageType.Double:
            return parameter.AsDouble()
        elif storage_type == DB.StorageType.String:
            return parameter.AsString()
        elif storage_type == DB.StorageType.ElementId:
            return parameter.AsElementId()
    return
